/* esm.sh - esbuild bundle(@radix-ui/react-tabs@1.0.4) denonext production */
import u from"../../../../../../esm.sh/@babel/runtime@7.23.1/helpers/esm/extends.js";
import{forwardRef as p,createElement as d,useRef as k,useEffect as H}from"../../../../../../esm.sh/preact@10.19.6/compat.js";
import{composeEventHandlers as v}from"../../../../../../esm.sh/_@radix-ui/primitive@1.0.1.js";
import{createContextScope as z}from"../../../../../../esm.sh/v132/_@radix-ui/react-context@1.0.1.js";
import{createRovingFocusGroupScope as g,Root as h,Item as S}from"../../../../../../esm.sh/v132/_@radix-ui/react-roving-focus@1.0.4.js";
import{Presence as E}from"../../../../../../esm.sh/v132/_@radix-ui/react-presence@1.0.1.js";
import{Primitive as m}from"../../../../../../esm.sh/v132/_@radix-ui/react-primitive@1.0.3.js";
import{useDirection as M}from"../../../../../../esm.sh/v132/_@radix-ui/react-direction@1.0.1.js";
import{useControllableState as R}from"../../../../../../esm.sh/v132/_@radix-ui/react-use-controllable-state@1.0.1.js";
import{useId as y}from"../../../../../../esm.sh/v132/_@radix-ui/react-id@1.0.1.js";
var T="Tabs",[A,Y]=z(T,[g]),_=g(),[P,I]=A(T),F=p((e,n)=>{let{__scopeTabs:c,value:t,onValueChange:s,defaultValue:i,orientation:o="horizontal",dir:b,activationMode:l="automatic",...f}=e,r=M(b),[a,$]=R({prop:t,onChange:s,defaultProp:i});return d(P,{scope:c,baseId:y(),value:a,onValueChange:$,orientation:o,dir:r,activationMode:l},d(m.div,u({dir:r,"data-orientation":o},f,{ref:n})))}),N="TabsList",V=p((e,n)=>{let{__scopeTabs:c,loop:t=!0,...s}=e,i=I(N,c),o=_(c);return d(h,u({asChild:!0},o,{orientation:i.orientation,dir:i.dir,loop:t}),d(m.div,u({role:"tablist","aria-orientation":i.orientation},s,{ref:n})))}),D="TabsTrigger",G=p((e,n)=>{let{__scopeTabs:c,value:t,disabled:s=!1,...i}=e,o=I(D,c),b=_(c),l=C(o.baseId,t),f=x(o.baseId,t),r=t===o.value;return d(S,u({asChild:!0},b,{focusable:!s,active:r}),d(m.button,u({type:"button",role:"tab","aria-selected":r,"aria-controls":f,"data-state":r?"active":"inactive","data-disabled":s?"":void 0,disabled:s,id:l},i,{ref:n,onMouseDown:v(e.onMouseDown,a=>{!s&&a.button===0&&a.ctrlKey===!1?o.onValueChange(t):a.preventDefault()}),onKeyDown:v(e.onKeyDown,a=>{[" ","Enter"].includes(a.key)&&o.onValueChange(t)}),onFocus:v(e.onFocus,()=>{let a=o.activationMode!=="manual";!r&&!s&&a&&o.onValueChange(t)})})))}),w="TabsContent",O=p((e,n)=>{let{__scopeTabs:c,value:t,forceMount:s,children:i,...o}=e,b=I(w,c),l=C(b.baseId,t),f=x(b.baseId,t),r=t===b.value,a=k(r);return H(()=>{let $=requestAnimationFrame(()=>a.current=!1);return()=>cancelAnimationFrame($)},[]),d(E,{present:s||r},({present:$})=>d(m.div,u({"data-state":r?"active":"inactive","data-orientation":b.orientation,role:"tabpanel","aria-labelledby":l,hidden:!$,id:f,tabIndex:0},o,{ref:n,style:{...e.style,animationDuration:a.current?"0s":void 0}}),$&&i))});function C(e,n){return`${e}-trigger-${n}`}function x(e,n){return`${e}-content-${n}`}var Z=F,ee=V,te=G,oe=O;export{oe as Content,ee as List,Z as Root,F as Tabs,O as TabsContent,V as TabsList,G as TabsTrigger,te as Trigger,Y as createTabsScope};
//# sourceMappingURL=react-tabs.mjs.map