/* esm.sh - esbuild bundle(@radix-ui/react-tabs@1.0.4) denonext production */
/* this file is created from "./Tabs.tsx" */
import*as n from"../../../../../../esm.sh/preact@10.19.6/compat.js";
import{composeEventHandlers as b}from"../../../../../../esm.sh/_@radix-ui/primitive@1.0.1.js";
import{createContextScope as P}from"../../../../../../esm.sh/v132/_@radix-ui/react-context@1.0.1.js";
import{createRovingFocusGroupScope as R}from"../../../../../../esm.sh/v132/_@radix-ui/react-roving-focus@1.0.4.js";
import{Primitive as p}from"../../../../../../esm.sh/v132/_@radix-ui/react-primitive@1.0.3.js";
import*as _ from"../../../../../../esm.sh/v132/_@radix-ui/react-roving-focus@1.0.4.js";
import{useDirection as w}from"../../../../../../esm.sh/v132/_@radix-ui/react-direction@1.0.1.js";
import{useControllableState as x}from"../../../../../../esm.sh/v132/_@radix-ui/react-use-controllable-state@1.0.1.js";
import{useId as D}from"../../../../../../esm.sh/v132/_@radix-ui/react-id@1.0.1.js";
const v="Tabs",[G,V]=P(v,[R]),y=R(),[L,g]=G(v),T=n.forwardRef((e,r)=>{const{__scopeTabs:c,value:t,onValueChange:i,defaultValue:u,orientation:o="horizontal",dir:l,activationMode:d="automatic",...m}=e,s=w(l),[a,f]=x({prop:t,onChange:i,defaultProp:u});return n.createElement(L,{scope:c,baseId:D(),value:a,onValueChange:f,orientation:o,dir:s,activationMode:d},n.createElement(p.div,{dir:s,"data-orientation":o,...m,ref:r}))});T.displayName=v;const A="TabsList",C=n.forwardRef((e,r)=>{const{__scopeTabs:c,loop:t=!0,...i}=e,u=g(A,c),o=y(c);return n.createElement(_.Root,{asChild:!0,...o,orientation:u.orientation,dir:u.dir,loop:t},n.createElement(p.div,{role:"tablist","aria-orientation":u.orientation,...i,ref:r}))});C.displayName=A;const h="TabsTrigger",E=n.forwardRef((e,r)=>{const{__scopeTabs:c,value:t,disabled:i=!1,...u}=e,o=g(h,c),l=y(c),d=S(o.baseId,t),m=F(o.baseId,t),s=t===o.value;return n.createElement(_.Item,{asChild:!0,...l,focusable:!i,active:s},n.createElement(p.button,{type:"button",role:"tab","aria-selected":s,"aria-controls":m,"data-state":s?"active":"inactive","data-disabled":i?"":void 0,disabled:i,id:d,...u,ref:r,onMouseDown:b(e.onMouseDown,a=>{!i&&a.button===0&&a.ctrlKey===!1?o.onValueChange(t):a.preventDefault()}),onKeyDown:b(e.onKeyDown,a=>{[" ","Enter"].includes(a.key)&&o.onValueChange(t)}),onFocus:b(e.onFocus,()=>{const a=o.activationMode!=="manual";!s&&!i&&a&&o.onValueChange(t)})}))});E.displayName=h;const M="TabsContent",I=n.forwardRef((e,r)=>{const{__scopeTabs:c,value:t,forceMount:i,children:u,...o}=e,l=g(M,c),d=S(l.baseId,t),m=F(l.baseId,t),s=t===l.value,a=n.useRef(s);n.useEffect(()=>{const N=requestAnimationFrame(()=>a.current=!1);return()=>cancelAnimationFrame(N)},[]);const f=i||s;return n.createElement(p.div,{"data-state":s?"active":"inactive","data-orientation":l.orientation,role:"tabpanel","aria-labelledby":d,hidden:!f,id:m,tabIndex:0,...o,ref:r,style:{...e.style,animationDuration:a.current?"0s":void 0}},f&&u)});I.displayName=M;function S(e,r){return`${e}-trigger-${r}`}function F(e,r){return`${e}-content-${r}`}const $=T,k=C,K=E,B=I;export{V as createTabsScope,T as Tabs,C as TabsList,E as TabsTrigger,I as TabsContent,$ as Root,k as List,K as Trigger,B as Content};
